description: BGPVPN networking example (admin)
heat_template_version: '2013-05-23'

parameters:
  cidr:
    type: string
    description : cidr of the subnet attached to the bgpvpn
    default : 10.0.0.0/24

resources:
  BGPVPN2:
    type: OS::Neutron::BGPVPN
    properties:
      route_targets: [ "100:1001"]
      name: "default VPN"

  Net2:
    type: OS::Neutron::Net

  SubNet2:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: Net2 }
      cidr: { get_param: cidr }

  BGPVPN_NET_assoc2:
    type: OS::Neutron::BGPVPN-NET-ASSOCIATION
    properties:
      bgpvpn_id: { get_resource: BGPVPN2 }
      network_id: { get_resource: Net2 }

